security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            provider: app_user_provider
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        admin:
            pattern: ^/admin
            provider: app_admin_provider
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
            logout:
                path: /admin/logout
                target: /admin/login
            stateless: false
            entry_point: form_login

        main:
            pattern: ^/
            provider: app_user_provider
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /
            logout:
                path: /logout
                target: /
            custom_authenticators:
                - App\Security\MyFacebookAuthenticator
            stateless: false
            entry_point: form_login

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
