vich_uploader:
    db_driver: orm

    mappings:
        bid_images:
            uri_prefix: /images/offers
            upload_destination: '%kernel.project_dir%/public/images/offers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
